### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by DomenicoLombardiGeoLab** [os-climate/OS-Climate-Community-Hub#85]
Requesting credentials for github user: DomenicoLombardiGeoLab

Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Email address to send a credential download link: domenicolombardi@gmail.com

Request checklist:
- [ X] User can establish connection with the bucket
- [ X] User can read files from the bucket
- [ X] User can write files to the bucket

**Comment by HeatherAck** [comment]
@ryanaslett I approve Domenico's request for credentials

**Comment by ryanaslett** [comment]
Hi we've recently rotated the keys, so if you were using them to access the bucket, you'll need to retrive them again. Since I havent heard back in a while, Im going to assume this solved the access issue for you, and close this ticket. 

Feel free to re-open or submit a new issue if you're still having access issues.
